// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvoSJxO-fPrCAC_YcNhkQe0boSFJKUb0c',
    appId: '1:888630957914:web:d301f6d31535a030d84563',
    messagingSenderId: '888630957914',
    projectId: 'nmtt-25391',
    authDomain: 'nmtt-25391.firebaseapp.com',
    storageBucket: 'nmtt-25391.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB5SKGLrizE4FeHwEvIJ75FceROfVe-Fs',
    appId: '1:888630957914:android:726bddc4c3a397cfd84563',
    messagingSenderId: '888630957914',
    projectId: 'nmtt-25391',
    storageBucket: 'nmtt-25391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcRubHIWbe218xzkJJ1pkrsVJOxYCQBLs',
    appId: '1:888630957914:ios:23bba1bcbb17da9fd84563',
    messagingSenderId: '888630957914',
    projectId: 'nmtt-25391',
    storageBucket: 'nmtt-25391.appspot.com',
    iosBundleId: 'com.example.crudappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcRubHIWbe218xzkJJ1pkrsVJOxYCQBLs',
    appId: '1:888630957914:ios:1a08745dcd28e3a0d84563',
    messagingSenderId: '888630957914',
    projectId: 'nmtt-25391',
    storageBucket: 'nmtt-25391.appspot.com',
    iosBundleId: 'com.example.crudappfirebase.RunnerTests',
  );
}
